### PR TITLE
[WIP] Start creating 2.7 ebuilds

### PR DESCRIPTION
**Pull request by davidrohr**
This is a first batch of 2.7 ebuilds.

Some are still missing: hcc, rocminfo, rocr-debug-agent, rocprofiler, roctracer, rocr-runtime, rocBLAS.
For these missing ones, I just used the 2.6 source or the master branch, but already created ebuild files to satisfy the dependencies.
THIS SHOULD NOT BE MERGED UNTIL 2.7 IS OUT, I'LL UPDATE THIS BRANCH WITH THE MISSING EBUILDS THEN! (or someone else can do so :|)
So far, I just wanted to share the work if someone wants to have a look.

Other changes:
- Moved / renamed the meta-ebuilds to dev-util (like e.g. CUDA)
- Added the `clang` use flag to `hip`, which will require a system clang installation and in that case build HIPIFY_CLANG, otherwise it is not built.
- Added `system-llvm-roc` use flags to `hip` and `rocm-opencl-runtime` to make them use the `llvm-roc` package. Otherwise, `hip` will use `hcc` and `rocm-opencl-runtime` will build clang itself.
In both cases, the `system-llvm-roc` is not yet working for me, but I thought adding the use flags is the best way to combine the previously separate build strategies in one ebuild.
- Changed `llvm-roc` to -DBUILD_SHARED_LIBS=Off like for `hcc`, since this solves some dependency issues.
- Added `sci-libs/hipCUB`, `dev-util/roctracer` (not yet working), `dev-util/clang-ocl` (not yet working)

Remaining issues:
- `hcc` installs a CMake module file that breaks if `find_package(hcc)` is used twice. This breaks some of the sci-libs packages, some already have workarounds, but I think this should be fixed in `hcc` itself.
- `roctracer` fails because a python script tries to download stuff during configure, need to have a look but seems rather complicated to fix this properly.
- `clang-ocl` has hardcoded checks for /opt/rocm, need to find the correct strategy to fix this.
- `rocBLAS` and `rocFFT` fail, didn't investigate further.

I spent some time further investigating the problem with `rocm-opencl-runtime` built v.s. `llvm-roc`. One problem is that `llvm-roc` builds the X86 backend, which is not done by `rocm-opencl-runtime`. If I disable this backend, and build `llvm-roc` only for AMDGPU, some of the linking issues disappear, but the opencl runtime is still not working. However, we use `llvm-roc` also for other packages (e.g. `hip` in the future, and there we need the X86 target), so removing X86 is probably not the correct strategy. Right now I have no idea any more. Anyhow, it can be enabled via the use flag if someone wants to try, by default it is off.

In general, I think we might want to streamline the installation directories, I'll open a separate issue for this.

### CODE REVIEW

**Comment by justxi** [comment]
Great work!
I just started to work, but good that I had a look =)...

**Comment by davidrohr** [comment]
:|
You are welcome, I am quite frustrated now.... Let's see if you can make more progress!

**Comment by justxi** [comment]
Comment on the other notes:
- For me the important problem is to build hip against llvm-roc, because currently there is no 2.7 branch for hcc

- I think we should keep building of rocm-opencl-runtime the old way, until hip works.
I spent a lot of hours on that, without success.

- roctracer - I wanted to install it, I will try it for 2.6. I had some other ebuils which want to download stuff, which I could solve, e.g. rocBLAS, where I submitted a patch to the ROCM team, to use local software

**Comment by justxi** [comment]
I appreciate your moves of the packages.
Yes sometimes I was frustrated too ;).
Thanks again for your work. 

We will solve the problems =).

**Comment by davidrohr** [comment]
>     * I think we should keep building of rocm-opencl-runtime the old way, until hip works.
>       I spent a lot of hours on that, without success.

I agree actually, this is not really working / foreseen right now, and I am not sure if it makes sense to spend many more hours on it. If we want to go that way, we should ask the AMD developers if this is supported. In the end, it doesn't make much difference either, since what comes out is one single library libamdocl64.so in any case. The main difference is compile-time, which is way longer if we need to build llvm/clang one additional time.

**Comment by davidrohr** [comment]
>     * For me the important problem is to build hip against llvm-roc, because currently there is no 2.7 branch for hcc, I don´t know if there will be one... and without HIP the libraries could not be build.

Perhaps we should check back with AMD if this is already supported. I just tried on redhat with their 2.6 RPMs. When I only set HIP_COMPILER to clang, it still uses hcc. When I set HIP_PLATFORM to clang, it basically breaks. There are already some cases implemented in the hipcc script, but they try to use an llvm compiler at /opt/ropm/llvm, which is not available from any of their RPMs. This indicates to me that at least in the official RPMs, hip without hcc is not yet working. Perhaps this has not yet been fully implemented.

**Comment by justxi** [comment]
Yes, in the past I took up to three hours to build it, but the latest took around 15-20 minutes. Thats current ok for me. If we use system llvm for this and want to build one single library, the llvm packages must provide static archives (*.a).

**Comment by justxi** [comment]
Regarding roctracer: I managed to build it without ebuild. But besides the python version, the downloaded content and some hardcoded paths, two of four tests fail. If you are interested I can provide a further information, to test it on your system.

**Comment by justxi** [comment]
I added an ebuild for "roctracer", it compiles and installs, but to use the tool there is more work todo.
Currently "gfx803" is hardcoded. This could be easily changed with USE flags.

**Comment by justxi** [comment]
I commited your work, so I can use the ebuilds for ROCM 2.7.

**Comment by justxi** [comment]
I will

**Pull request merged**
