### PR TITLE
Fixes and updates to 2.0.0

### PR DESCRIPTION
**Pull request by davidrohr**
Hi, I just came accross your repository trying to compile ROCm on my gentoo machine, so thanks a lot, saved me a lot of work.
Several things needed to be fixed, accumulated in this PR.
As you seem to be integrating 2.0.0 right now, and anyway changing the structure to allow porting to the official gentoo repository, I am not sure how much you are interested in longer PRs, therefore I just fixed what I needed. (Trying to avoid collisions / redundant work)
Please have a look, in case you are interested, I would gladly help you test and update stuff for 2.0.

Currently, I have still 2 issues which I had to fix "manually", I do not know if you are aware of:
- I need to set FEATURES=-network-sandbox, otherwise the rocm-opencl-runtime/driver will not complain, as it tries to download google-test during the compilation.
- rocm-opencl-runtime produces some file-collisions with rocm-device-libs and rocm-opencl-driver.

### CODE REVIEW

**Comment by davidrohr** [comment]
On top of what I wrote before, I found two more things:
- rocm-opencl-runtime has problems during linking, since the linker flags miss -L /usr/lib/llvm/roc-2.0.0/lib and it does not find LLVM/clang. I do not know why, as the LLVM dir is passed in via cmake correctly. Do you see the same issue?
- In general, I think one could switch from fetching git tags to downloading github tag tarballs. I tried that for hcc, but it fails because hcc has linked git repositories, i.e. the hcc git repo also clones llvm, but the tarball does not contain the llvm sources. So one could fetch both hcc and llvm tarball and place it in the correct folder inside hcc. However, I am wondering why we need llvm at all. As far as I can tell, llvm-roc already installs llvm, so hcc should use this installation, or do I miss something?

**Comment by davidrohr** [comment]
Last comment for today: It seems hip is build either v.s. nvcc or v.s. hcc as compiler. I didn't find a way to enable both in CMake, did you? As people (like me) might want to test both NVIDIA and AMD cards, perhaps one could come up with a way to provide both, e.g. we could create two packackes hip-hcc and hip-nvcc?

**Comment by justxi** [comment]
> 
> 
> On top of what I wrote before, I found two more things:
> 
>     * rocm-opencl-runtime has problems during linking, since the linker flags miss -L /usr/lib/llvm/roc-2.0.0/lib and it does not find LLVM/clang. I do not know why, as the LLVM dir is passed in via cmake correctly. Do you see the same issue?

Yes thats where I currently stuck... that is a WIP ebuild...

> 
>     * In general, I think one could switch from fetching git tags to downloading github tag tarballs. I tried that for hcc, but it fails because hcc has linked git repositories, i.e. the hcc git repo also clones llvm, but the tarball does not contain the llvm sources. So one could fetch both hcc and llvm tarball and place it in the correct folder inside hcc. However, I am wondering why we need llvm at all. As far as I can tell, llvm-roc already installs llvm, so hcc should use this installation, or do I miss something?

Yes, I currently try to use tarballs instead of git, that would make re/new installs faster. Building llvm standalone and using it in the packages makes problems. llvm-roc is a try to remove it from rocm-opencl-runtime. Later I hope llvm-rocm is in the upstream llvm repo so we can use the ebuild for llvm which is already in portage.

**Comment by justxi** [comment]
> 
> 
> Last comment for today: It seems hip is build either v.s. nvcc or v.s. hcc as compiler. I didn't find a way to enable both in CMake, did you? As people (like me) might want to test both NVIDIA and AMD cards, perhaps one could come up with a way to provide both, e.g. we could create two packackes hip-hcc and hip-nvcc? (Actually that is the way other distros are handling this it seems: https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md)

Yes hat would be a nice solution because I also want to try both, but this has to be solved when the other packages/ebuilds are ready.

**Comment by davidrohr** [comment]
Hi Wilfried, thx for the fast replies. Indeed I think having llvl (and clang) separate and using the upstream version sometime in the future is the right way to go. Then we should also make hcc use these instead of fetching the packages again.
Perhaps we could also add a general rocm metapacke that installs the full suite, currently for a newcomer it is difficult to see what ue needs.

I will let you do the restructuring work and am happy to try it out once you are done or in between.

 In the meantime, i'll look into hip-hcc and hip-nvcc. I hope this way we do not collide.
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by justxi** [comment]
Hi,
a meta package is a good idea.
I think we will not collide, because I think a working ebuild is a working ebuild. At the end to get it accepted by the gentoo maintainers, it must conform to their rules. Furthermore due to the fact that the building system of rocm works for AMD, but does not comply all Gentoo rules, all knowlege you can gain will help to make the ebuilds better.

**Pull request merged**
