### PR TITLE
WIP 4.2.0 ebuilds tested on a vega64, gentoo-source 5.10 and against pre-packages libtorch rocm4.2

### PR DESCRIPTION
**Pull request by fuag15**

### CODE REVIEW

**Comment by justxi** [comment]
Thanks for your work. 
I accept the patch and will try to check it on my system.

**Comment by littlewu2508** [comment]
@fuag15  That's very impressive! I just plan to upgrade all these ebuilds to 4.2, and get them merged into portage and science overlay.

BTW, we have existing discussion about hip-4.2 : https://bugs.gentoo.org/799257 and https://github.com/justxi/rocm/issues/192
and I have a [plan for cleanup rocBLAS ebuild](https://github.com/justxi/rocm/issues/194).

Also, could you share more information about libtorch? We have a working sci-libs/pytorch with rocm support in science overlay and I'm about to upgrade it to the latest version after bumping rocm to 4.2.

**Comment by littlewu2508** [comment]
I'm also interested in the GPU you used. I have a Radeon VII and meet the [driver compatibility issue](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html#driver-compability-issue-in-rocm-v4-1). This isn't solved until Linux 5.13 (or use the AMD rock kernel, which is only 5.9). so you success with gentoo-source 5.10 combined with rocm-4.2, so that means Vega64 is not in the "buggy GPU" list (AMD said it contains 7nm based hardware, including Vega20 and MI50/60), right?

**Comment by fuag15** [comment]
Awesome! :)  This might have been a bit premature, I did more clean up last night and got the existing ebuilds into a good state on my machine. I'm working this weekend on updating rocFFT to use hipFFT and hammering away at the pytorch 1.9 ebuilds from aclex-pytorch.

RE: Gpu and Kernel issues

I got lucky on that by being out of date, the vega 64 is pre-7nm. (Vega10) I haven't done much extensive testing however... The blind test i did was to use a prepackaged pytorch 1.9 rocm4.2 to train on the gpu. rocminfo complains that there is no ROCk kernel module but everything else seems to be happy.

I'll update with another pr on the other side of the rocFFT / hipFFT and pytorch1.9 ebuilds. Hopefully at the end of the weekend.

**Comment by fuag15** [comment]
ok, i ran into some bugs actually working against that set of ebuilds and have updated, the working state compiles pytorch-1.9.0 successfully with rocm support on a gfx900 (vega 64) system on gentoo-sources-5.10.48

**Pull request closed without merging**
