### PR TITLE
sci-libs/rocALUTION: reflect dist checksum change

### PR DESCRIPTION
**Pull request by aclex**
The distribution archive of `rocALUTION` was changed upstream for the unknown reason, so the checksums are now differ and installation fails for me. Could you please check, if it's reproducible in your environment, too? I'm not completely sure, if the new checksum is valid, don't see the reason the archive is changed, but for any case the updated `Manifest` is also applied here.

### CODE REVIEW

**Comment by justxi** [comment]
I will check it.

**Comment by aclex** [comment]
@justxi thank you!

**Comment by fuag15** [comment]
thanks so much for these builds btw. this fixed it for me

**Comment by aclex** [comment]
@justxi sorry for asking again, have you had a chance to check the checksum mismatch on your installation? I'm building a Gentoo Docker image with ROCm infrastructure installed, it fails because of this mismatch issue, but I still haven't managed to change the checksum manually (naive manifest editing is simply ignored somehow). So if it's fixed, I'll be able to finish the image for version 3.0.0, which appears to be most stable for now.

**Comment by justxi** [comment]
Sorry...  and now my results: 
My file which I used to create the commited Manifest for rocALUTION 3.0.0 was downloaded on 19th of Dec and has a filesize of 1434962 bytes. 

I downloaded the current file for rocALUTION 3.0.0, which was crated on 5th of Feb 2020, which has a filesize of 1434964 bytes - two bytes more.

I think the archive was change and therefore the Manifest must be updated.

**Comment by aclex** [comment]
@justxi no problem at all, thank you very much for checking it! Don't have the previous version of that file myself, so yes, now it's quite obvious, seems the source archive has been changed.
I'll rebase the commit in this request now then.

**Comment by aclex** [comment]
Many thanks for merging it! I'll report, as ROCm-3.0 Docker image is completed.

**Comment by aclex** [comment]
As promised, here's a link to a Docker image I've uploaded to Docker hub: https://hub.docker.com/r/aclex/gentoo-rocm It's for `gfx906` only yet, don't know what to do with other architectures, actually, is the unified package (not possible now) is better, than several specified ones (more in spirit of Gentoo).

**Pull request merged**
