### PR TITLE
Fix rocminfo on Gentoo with Python 3 + some minor other fixes

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
Hm, for me the python code is not compatible. Running `rocm_agent_enumerator` with python3 yields:
`File "./rocm_agent_enumerator", line 141`
`print "gfx000"`
`SyntaxError: Missing parentheses in call to 'print'. Did you mean print("gfx000")?`

Perhaps this was fixed in the current development version of rocminfo, as the latest tagged version os only 1.0.0 for some reason (which is the version I am fixing with this PR).

**Comment by justxi** [comment]
I created a PR for this. I think instead of limiting it to python2 add the parenthesis (https://github.com/justxi/rocminfo/commit/0b5ccf90fa8824fde9b8f889e0904f89234ed3c3).

**Comment by davidrohr** [comment]
That is indeed better, I'll update my PR to remove the python2 requirement later.
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by davidrohr** [comment]
@justxi : Well, on second thought, your PR will not become part of rocminfo-1.0.0.
So I'd actually accept this PR as is, and then we create a new up to date rocminfo version once the patch is accepted. Anyhow, perhaps we should not use 1.0.0 in the end, as it is one year old and lacks several other fixed.
We could do some naming based on the date, i.e. when your PR is accepted, we create a rocminfo-201902?? that has the master branch from that time and will support python 3?

**Comment by justxi** [comment]
ok

**Pull request merged**
