### PR TITLE
Install `sci-libs/hipCUB` to `lib64`

### PR DESCRIPTION
**Pull request by aclex**
To be consistent with Gentoo layout and the rest of the ROCm packages.

With this fix from PyTorch point of view there're only hcc and hip in `lib` remaining.

### CODE REVIEW

**Comment by justxi** [comment]
If the install location of hcc and hip are changed, I think all ebuilds which depend on these must be change.

**Comment by aclex** [comment]
Thanks for the merge! Yes, I completely agree, for hcc and hip this change looks quite major due to possible dependencies, so maximum care must be taken, not thinking of changing them at the moment.

**Comment by justxi** [comment]
If all is usable to install pytorch then we keep it as it is.
For the next ROCm release we can think about to change it.

**Comment by aclex** [comment]
Yes, I seem to manage building pytorch versions 1.3.0 and 1.3.1 successfully, which are also seem to work (haven't performed the full test coverage recommended by AMD, yet) and almost there for version 1.4.0, so yes, it's obviously fine for now. After that I plan to write the results here to maybe move certain packages used by pytorch from untested to tested on the main page, if you would want.

**Comment by justxi** [comment]
> Yes, I seem to manage building pytorch versions 1.3.0 and 1.3.1 successfully, which are also seem to work (haven't performed the full test coverage recommended by AMD, yet) and almost there for version 1.4.0, so yes, it's obviously fine for now. After that I plan to write the results here to maybe move certain packages used by pytorch from untested to tested on the main page, if you would want.

Yes, that would be good.

**Pull request merged**
